[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "posawesome"
authors = [
    { name = "POS Awesome Developers" }
]
description = "POS Awesome for ERPNext"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = []

[tool.flit.module]
name = "posawesome"
